name: Validate AZD template
on:
  push:
    branches: [ aca-openai-agent ]
    paths:
      - "infra/**"
  pull_request:
    branches: [ main ]
    paths:
      - "infra/**"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upgrade bicep
        run: |
          which bicep
          sudo curl -o $(which bicep) -L https://github.com/Azure/bicep/releases/download/v0.31.92/bicep-linux-x64
          sudo chmod +x $(which bicep)

      - name: Build Bicep for linting
        uses: azure/CLI@v1
        with:
          inlineScript: bicep build -f infra/main.bicep --stdout

      - name: Run PSRule analysis
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: PSRule.Rules.Azure
          baseline: Azure.Pillar.Security
          inputPath: infra/*.test.bicep
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          summary: true
        continue-on-error: true
          
        env:
          PSRULE_CONFIGURATION_AZURE_BICEP_FILE_EXPANSION: 'true'
          PSRULE_CONFIGURATION_AZURE_BICEP_FILE_EXPANSION_TIMEOUT: '30'

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: github.repository == 'Azure-Samples/contoso-creative-writer'
        with:
          sarif_file: reports/ps-rule-results.sarif
